language: node_js
node_js:
  - "12"
before_script:
  - npm install
script: npm run build
deploy:
  local-dir: dist/nation_sound
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN == Set in travis-ci.org dashboard, marked secure
  on:
    branch: main
notifications:
  email: false
