language: node_js
node_js:
  - "12"
before_script:
  - npm install
script:
  - ng build --prod
deploy:
  provider: pages
  local_dir: ./dist/nation_sound
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    repo: main
notifications:
  email: false
