language: node_js
node_js:
  - "14"
before_script:
  - npm install
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  on:
    branch: main
notifications:
  email: false
